"""Run the calibration campaign end to end, committing as it goes.

Designed to be left unattended. Each phase generates its plan, measures every
cell, and commits the resulting data before the next phase starts, so an
interrupted campaign leaves committed work behind rather than an untracked
pile — and a resumed one skips what is already recorded.

    python campaign.py                       # every phase, in order
    python campaign.py --phases phase4 phase5
    python campaign.py --dry-run             # print the plan sizes and stop

Phases run cheapest-first on purpose: the screening phases decide which
factors the expensive ones need to vary, and a failure early is cheap.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import time
from pathlib import Path

HERE = Path(__file__).parent
DATA = HERE / "data"
ORDER = ["phase0", "phase1", "phase2", "phase2b", "phase3", "phase4", "phase5"]

# Host memory to leave free per phase. The holdout phase runs the production
# hybrids, whose whole point is that they nearly fill the machine, so it gets
# a smaller margin — still enough that the kernel is not pushed into reclaim,
# but not so much that the phase skips the models it exists to validate.
HEADROOM_GIB = {"phase5": 10.0}
DEFAULT_HEADROOM_GIB = 30.0


def run(cmd: list[str], **kw) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, cwd=HERE.parents[1], text=True, **kw)


def commit(paths: list[Path], message: str) -> None:
    """Commit the phase's data, tolerating there being nothing new to commit."""
    run(["git", "add", "--"] + [str(p) for p in paths])
    staged = run(["git", "diff", "--cached", "--quiet", "--"] +
                 [str(p) for p in paths])
    if staged.returncode == 0:
        print("    (nothing new to commit)", flush=True)
        return
    result = run(["git", "commit", "-m", message], capture_output=True)
    if result.returncode != 0:
        # Signing can fail if the agent's key is gone. Say so loudly and keep
        # measuring: the data is on disk either way, and losing the rest of an
        # overnight campaign to a commit failure would be the worse outcome.
        print(f"    COMMIT FAILED (data is still on disk): "
              f"{result.stderr.strip().splitlines()[:1]}", flush=True)
        return
    print(f"    committed {message.splitlines()[0]}", flush=True)


def phase(name: str, headroom: float, load_timeout: int) -> None:
    plan_path = DATA / f"{name}-plan.json"
    out_path = DATA / f"{name}.ndjson"
    plan = run([sys.executable, str(HERE / "plan.py"), name], capture_output=True)
    if plan.returncode != 0:
        print(f"  {name}: plan generation failed: {plan.stderr}", flush=True)
        return
    plan_path.parent.mkdir(parents=True, exist_ok=True)
    plan_path.write_text(plan.stdout)
    cells = len(json.loads(plan.stdout))

    print(f"\n=== {name}: {cells} cells, {headroom:.0f} GiB headroom ===", flush=True)
    started = time.monotonic()
    run([sys.executable, str(HERE / "measure.py"), "--out", str(out_path),
         "--plan", str(plan_path), "--headroom-gib", str(headroom),
         "--load-timeout", str(load_timeout)])
    minutes = (time.monotonic() - started) / 60

    done = sum(1 for line in out_path.read_text().splitlines() if line.strip()) \
        if out_path.exists() else 0
    commit([out_path, plan_path],
           f"data(calibration): {name} measurements\n\n"
           f"{done} records over {cells} planned cells, {minutes:.0f} minutes on "
           f"this machine. Generated by scripts/calibration/plan.py and measured "
           f"by measure.py; see the phase's docstring in plan.py for what it "
           f"covers and why.")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--phases", nargs="+", default=ORDER, choices=ORDER)
    parser.add_argument("--load-timeout", type=int, default=2400,
                        help="seconds to wait for a model to load; a 200 GiB "
                             "--no-mmap load takes minutes")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    if args.dry_run:
        for name in args.phases:
            plan = run([sys.executable, str(HERE / "plan.py"), name],
                       capture_output=True)
            print(f"{name}: {len(json.loads(plan.stdout))} cells")
        return 0

    for name in args.phases:
        phase(name, HEADROOM_GIB.get(name, DEFAULT_HEADROOM_GIB), args.load_timeout)

    print("\ncampaign complete", flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
