[package]
name = "ananke-placement"
edition.workspace = true
version.workspace = true

[dependencies]
ananke-config.workspace = true
ananke-estimate.workspace = true
smol_str.workspace = true
tracing.workspace = true

[dev-dependencies]
ananke-fs.workspace = true
ananke-gguf.workspace = true
serde_json.workspace = true
