//! Build-time glue that produces `../frontend/dist` before the main crate
//! compiles so `rust-embed` can fold the built assets into the binary.
//!
//! The flow is deliberately conservative: cargo only re-runs this script
//! when one of the listed frontend inputs changes, and we run `npm ci`
//! only on the first build (when `node_modules` is missing). A `npm run
//! build` on a clean tree is ~1 second — cheap enough not to feature-
//! flag.
//!
//! Set `ANANKE_SKIP_FRONTEND_BUILD=1` to skip the npm invocation entirely
//! — useful for Rust-only dev loops or for packaging that builds the
//! frontend separately and drops the assets into `../frontend/dist`
//! out-of-band.

use std::{
    path::{Path, PathBuf},
    process::Command,
};

fn main() {
    generate_tuning_constants();

    if std::env::var_os("ANANKE_SKIP_FRONTEND_BUILD").is_some() {
        return;
    }

    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let frontend = manifest_dir.parent().unwrap().join("frontend");

    // Re-run when any frontend input changes. `cargo:rerun-if-changed` on a
    // directory does *not* reliably detect an in-place edit of a nested file
    // (the intermediate directory mtimes don't change), so a change to e.g.
    // `src/locales/en/translation.json` would leave the embedded bundle stale.
    // Emit one `rerun-if-changed` per file by walking the tree instead.
    let watched = [
        "src",
        "index.html",
        "package.json",
        "package-lock.json",
        "vite.config.ts",
        "tsconfig.json",
        "tsconfig.app.json",
        "tsconfig.node.json",
        "eslint.config.js",
    ];
    for rel in watched {
        watch_recursively(&frontend.join(rel));
    }
    println!("cargo:rerun-if-env-changed=ANANKE_SKIP_FRONTEND_BUILD");

    // `npm ci` only when `node_modules` is absent; routine builds skip it.
    if !frontend.join("node_modules").exists() {
        run("npm", &["ci", "--legacy-peer-deps"], &frontend, "npm ci");
    }

    run("npm", &["run", "build"], &frontend, "npm run build");

    let index_html = frontend.join("dist").join("index.html");
    assert!(
        index_html.exists(),
        "frontend build did not produce {}",
        index_html.display()
    );
}

/// Turn `src/estimator/tuning.json` into compile-time constants.
///
/// The JSON is generated by `scripts/calibration/analyse.py` from the
/// measurement dataset, and it is the source of truth: the value a constant
/// has here *is* the value the estimator uses, so a number cannot drift from
/// the data that justifies it without the drift being visible in a diff of
/// the generated file. Each constant's `evidence` becomes part of its doc
/// comment, so the justification travels with the value rather than living in
/// a comment someone can forget to update.
fn generate_tuning_constants() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let source = manifest_dir.join("src/estimator/tuning.json");
    println!("cargo:rerun-if-changed={}", source.display());

    let raw = std::fs::read_to_string(&source)
        .unwrap_or_else(|e| panic!("reading {}: {e}", source.display()));
    let parsed: serde_json::Value =
        serde_json::from_str(&raw).unwrap_or_else(|e| panic!("parsing {}: {e}", source.display()));
    let constants = parsed
        .get("constants")
        .and_then(|c| c.as_object())
        .unwrap_or_else(|| panic!("{} has no `constants` object", source.display()));

    let mut out =
        String::from("// @generated by build.rs from src/estimator/tuning.json — do not edit.\n\n");
    for (name, spec) in constants {
        let ty = spec
            .get("type")
            .and_then(|v| v.as_str())
            .unwrap_or_else(|| panic!("{name}: missing `type`"));
        let raw = spec
            .get("value")
            .unwrap_or_else(|| panic!("{name}: missing `value`"));
        // A float literal has to keep its decimal point to be a float in
        // Rust, and an integer must not gain one.
        let value = if ty.starts_with('f') {
            let f = raw
                .as_f64()
                .unwrap_or_else(|| panic!("{name}: `value` is not a number"));
            if f.fract() == 0.0 {
                format!("{f:.1}")
            } else {
                f.to_string()
            }
        } else {
            raw.as_u64()
                .unwrap_or_else(|| panic!("{name}: `value` is not a non-negative integer"))
                .to_string()
        };
        let doc = spec.get("doc").and_then(|v| v.as_str()).unwrap_or("");
        let evidence = spec.get("evidence").and_then(|v| v.as_str()).unwrap_or("");

        for line in wrap(doc, 72) {
            out.push_str(&format!("/// {line}\n"));
        }
        out.push_str("///\n/// # Evidence\n///\n");
        for line in wrap(evidence, 72) {
            out.push_str(&format!("/// {line}\n"));
        }
        out.push_str(&format!("pub const {name}: {ty} = {value};\n\n"));
    }

    out.push_str(&generate_curves(&parsed));
    out.push_str(&generate_ik_rates(&parsed));
    out.push_str(&generate_rate_table(
        &parsed,
        "tensor_split_baseline",
        "TENSOR_SPLIT_BASELINE",
        "TENSOR_SPLIT_BASELINE_DEFAULT",
        "Extra host baseline bytes a tensor split costs beyond a layer split,\n/// by architecture.",
    ));
    out.push_str(&generate_signed_rate_table(
        &parsed,
        "baseline_offset",
        "BASELINE_OFFSET",
        "BASELINE_OFFSET_DEFAULT",
        "Correction to the process baseline the layer-count model leaves behind,\n/// by architecture and variant. Keys carry a `+moe`/`+e` suffix where those\n/// distinctions separate models that share an architecture string.",
    ));
    out.push_str(&generate_rate_table(
        &parsed,
        "checkpoint_headroom_bytes",
        "CHECKPOINT_HEADROOM_BYTES",
        "CHECKPOINT_HEADROOM_DEFAULT",
        "Host memory a real prompt adds over a short one, by architecture,\n/// from llama.cpp's context checkpoints. Reserved as slop.",
    ));
    out.push_str(&generate_rate_table(
        &parsed,
        "per_slot_host_bytes",
        "PER_SLOT_HOST_BYTES",
        "PER_SLOT_HOST_BYTES_DEFAULT",
        "Host memory each concurrently active slot costs beyond the first, by\n/// architecture. Reserved as slop, never charged to the correction.",
    ));
    out.push_str(&generate_rate_table(
        &parsed,
        "mtp_compute_intermediates",
        "MTP_COMPUTE_INTERMEDIATES",
        "MTP_COMPUTE_INTERMEDIATES_DEFAULT",
        "n_embd-wide f32 graph intermediates the MTP draft context holds live per\n/// batch token, by architecture.",
    ));
    out.push_str(&generate_rate_table(
        &parsed,
        "tensor_compute_intermediates",
        "TENSOR_COMPUTE_INTERMEDIATES",
        "TENSOR_COMPUTE_INTERMEDIATES_DEFAULT",
        "n_embd-wide f32 graph intermediates a tensor split holds live per batch\n/// token, by architecture.",
    ));
    out.push_str(&generate_rate_table(
        &parsed,
        "tensor_compute_quantised_rates",
        "TENSOR_COMPUTE_QUANTISED_RATES",
        "TENSOR_COMPUTE_QUANTISED_RATE_DEFAULT",
        "Extra tensor-split compute bytes per (batch token x context token) when\n/// the KV cache is quantised, by architecture.",
    ));
    out.push_str(&generate_rate_table(
        &parsed,
        "tensor_compute_shadow_bytes",
        "TENSOR_COMPUTE_SHADOW_BYTES",
        "TENSOR_COMPUTE_SHADOW_BYTES_DEFAULT",
        "Per-device VRAM llama.cpp cannot attribute — CUDA context, cuBLAS\n/// workspaces, driver bookkeeping — by architecture.",
    ));
    out.push_str(&generate_rate_table(
        &parsed,
        "no_flash_attn_score_bytes",
        "NO_FLASH_ATTN_SCORE_BYTES",
        "NO_FLASH_ATTN_SCORE_BYTES_DEFAULT",
        "Bytes of unfused attention score matrix per (head x cache token x batch\n/// token), by architecture.",
    ));
    out.push_str(&generate_rate_table(
        &parsed,
        "no_flash_attn_rates",
        "NO_FLASH_ATTN_RATES",
        "NO_FLASH_ATTN_RATE_DEFAULT",
        "Extra pinned bytes per batch token when flash attention is off, by\n/// architecture and variant. Flat in context, proportional to batch.",
    ));
    out.push_str(&generate_rate_table(
        &parsed,
        "quantised_cache_rates",
        "QUANTISED_CACHE_RATES",
        "QUANTISED_CACHE_RATE_DEFAULT",
        "Extra pinned bytes per batch token when the KV cache is quantised, by\n/// architecture.",
    ));

    let dest = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("tuning_constants.rs");
    std::fs::write(&dest, out).unwrap_or_else(|e| panic!("writing {}: {e}", dest.display()));
}

/// Turn the ordered compute-buffer curve table into a static slice.
///
/// The architecture-to-curve mapping is data, not logic: adding an
/// architecture should be a JSON edit, not a new match arm. Order is
/// significant and preserved — the first entry whose arch list contains the
/// model's architecture wins, so a variant-guarded entry has to precede the
/// general one for the same arch.
fn generate_curves(parsed: &serde_json::Value) -> String {
    let curves = match parsed.get("compute_buffer_curves") {
        Some(c) => c,
        None => return String::new(),
    };
    let mut out = String::from(
        "\n/// A per-architecture GPU compute-buffer curve: \
         `base_mib + base_batch_mib * k + slope_mib_per_1k * (ctx / 1024) * k`, \
         where `k = ubatch / 512`, per device.\n\
         #[derive(Debug, Clone, Copy)]\n\
         pub struct Curve {\n\
         \x20   /// Architectures this curve applies to.\n\
         \x20   pub archs: &'static [&'static str],\n\
         \x20   /// A variant discriminator the caller must also match, where one\n\
         \x20   /// architecture string covers models with different graphs.\n\
         \x20   pub variant: Option<&'static str>,\n\
         \x20   pub base_mib: u32,\n\
         \x20   /// A constant that scales with the batch but not the context —\n\
         \x20   /// large on some architectures, and with nowhere to go in a\n\
         \x20   /// two-term curve but the flat base or the margin.\n\
         \x20   pub base_batch_mib: u32,\n\
         \x20   pub slope_mib_per_1k: u32,\n\
         \x20   /// Whether the slope is linear in ubatch off the 512-token\n\
         \x20   /// calibration point.\n\
         \x20   pub slope_scales_with_ubatch: bool,\n\
         }\n\n",
    );

    let entries = curves
        .get("entries")
        .and_then(|e| e.as_array())
        .unwrap_or_else(|| panic!("compute_buffer_curves has no `entries` array"));
    out.push_str("/// Ordered; first match wins.\npub static CURVES: &[Curve] = &[\n");
    for entry in entries {
        out.push_str(&curve_literal(entry));
    }
    out.push_str("];\n\n");

    let default = curves
        .get("default")
        .unwrap_or_else(|| panic!("compute_buffer_curves has no `default`"));
    out.push_str(
        "/// Used by any architecture without its own entry.\npub static DEFAULT_CURVE: Curve = ",
    );
    out.push_str(curve_literal(default).trim().trim_end_matches(','));
    out.push_str(";\n");
    out
}

/// Per-architecture rates for ik's CPU-resident MoE intermediates.
///
/// One number cannot serve every architecture: the measured rates differ by a
/// third, so a single value either under-reserves the worst or over-reserves
/// the rest.
fn generate_ik_rates(parsed: &serde_json::Value) -> String {
    let Some(rates) = parsed.get("ik_moe_rates") else {
        return String::new();
    };
    let default = rates.get("default").and_then(|v| v.as_u64()).unwrap_or(0);
    let by_arch = rates.get("by_arch").and_then(|v| v.as_object());
    let mut out = String::from(
        "\n/// Bytes per batch token per unit of hidden size for ik's \
         CPU-resident\n/// MoE intermediates, by architecture.\n\
         pub static IK_MOE_RATES: &[(&str, u64)] = &[\n",
    );
    if let Some(map) = by_arch {
        for (arch, value) in map {
            out.push_str(&format!(
                "    ({arch:?}, {}),\n",
                value.as_u64().unwrap_or(default)
            ));
        }
    }
    out.push_str(
        "];\n\n/// Applied to an ik mixture of experts this dataset has \
                  not measured.\npub const IK_MOE_RATE_DEFAULT: u64 = ",
    );
    out.push_str(&default.to_string());
    out.push_str(";\n");
    out
}

/// A per-architecture rate table: `&[(arch, value)]` plus a default.
/// The same table, for values that may be negative.
///
/// `baseline_offset` corrects a baseline that over-covers as well as one that
/// under-covers, so its entries are signed. Reading them through the unsigned
/// path silently turns every negative into the default, which is zero — the
/// correction would vanish rather than fail.
fn generate_signed_rate_table(
    parsed: &serde_json::Value,
    key: &str,
    table: &str,
    default_name: &str,
    doc: &str,
) -> String {
    let Some(rates) = parsed.get(key) else {
        return String::new();
    };
    let default = rates.get("default").and_then(|v| v.as_i64()).unwrap_or(0);
    let mut out = format!("\n/// {doc}\npub static {table}: &[(&str, i64)] = &[\n");
    if let Some(map) = rates.get("by_arch").and_then(|v| v.as_object()) {
        for (arch, value) in map {
            out.push_str(&format!(
                "    ({arch:?}, {}),\n",
                value.as_i64().unwrap_or(default)
            ));
        }
    }
    out.push_str(&format!(
        "];\n\n/// Applied to an architecture this dataset has not measured.\n\
         pub const {default_name}: i64 = {default};\n"
    ));
    out
}

fn generate_rate_table(
    parsed: &serde_json::Value,
    key: &str,
    table: &str,
    default_name: &str,
    doc: &str,
) -> String {
    let Some(rates) = parsed.get(key) else {
        return String::new();
    };
    let default = rates.get("default").and_then(|v| v.as_u64()).unwrap_or(0);
    let mut out = format!("\n/// {doc}\npub static {table}: &[(&str, u64)] = &[\n");
    if let Some(map) = rates.get("by_arch").and_then(|v| v.as_object()) {
        for (arch, value) in map {
            out.push_str(&format!(
                "    ({arch:?}, {}),\n",
                value.as_u64().unwrap_or(default)
            ));
        }
    }
    out.push_str(&format!(
        "];\n\n/// Applied to an architecture this dataset has not measured.\n\
         pub const {default_name}: u64 = {default};\n"
    ));
    out
}

fn curve_literal(entry: &serde_json::Value) -> String {
    let archs: Vec<String> = entry
        .get("archs")
        .and_then(|a| a.as_array())
        .map(|a| {
            a.iter()
                .map(|v| format!("{:?}", v.as_str().unwrap_or_default()))
                .collect()
        })
        .unwrap_or_default();
    let variant = match entry.get("variant").and_then(|v| v.as_str()) {
        Some(v) => format!("Some({v:?})"),
        None => "None".to_string(),
    };
    let number = |key: &str| {
        entry
            .get(key)
            .and_then(|v| v.as_u64())
            .unwrap_or_else(|| panic!("curve entry missing `{key}`"))
    };
    let base_batch = entry
        .get("base_batch_mib")
        .and_then(|v| v.as_u64())
        .unwrap_or(0);
    let scales = entry
        .get("slope_scales_with_ubatch")
        .and_then(|v| v.as_bool())
        .unwrap_or(false);
    let evidence = entry.get("evidence").and_then(|v| v.as_str()).unwrap_or("");
    let mut out = String::new();
    for line in wrap(evidence, 68) {
        out.push_str(&format!("    // {line}\n"));
    }
    out.push_str(&format!(
        "    Curve {{ archs: &[{}], variant: {variant}, base_mib: {}, \
         base_batch_mib: {base_batch}, slope_mib_per_1k: {}, \
         slope_scales_with_ubatch: {scales} }},\n",
        archs.join(", "),
        number("base_mib"),
        number("slope_mib_per_1k"),
    ));
    out
}

/// Break `text` into lines of at most `width`, so generated doc comments do
/// not arrive as one unreadable line.
fn wrap(text: &str, width: usize) -> Vec<String> {
    let mut lines = Vec::new();
    let mut current = String::new();
    for word in text.split_whitespace() {
        if !current.is_empty() && current.len() + 1 + word.len() > width {
            lines.push(std::mem::take(&mut current));
        }
        if !current.is_empty() {
            current.push(' ');
        }
        current.push_str(word);
    }
    if !current.is_empty() {
        lines.push(current);
    }
    if lines.is_empty() {
        lines.push(String::new());
    }
    lines
}

/// Emit `cargo:rerun-if-changed` for `path` and, if it is a directory, every
/// file beneath it — watching each file individually so an in-place edit of a
/// nested source triggers a rebuild. Also watches the directories themselves,
/// so adding or removing a file is caught. Skips `node_modules` and `dist`,
/// which are build inputs/outputs, not sources.
fn watch_recursively(path: &Path) {
    println!("cargo:rerun-if-changed={}", path.display());
    if !path.is_dir() {
        return;
    }
    if matches!(
        path.file_name().and_then(|n| n.to_str()),
        Some("node_modules") | Some("dist")
    ) {
        return;
    }
    let Ok(entries) = std::fs::read_dir(path) else {
        return;
    };
    for entry in entries.flatten() {
        watch_recursively(&entry.path());
    }
}

fn run(cmd: &str, args: &[&str], cwd: &std::path::Path, label: &str) {
    let status = Command::new(cmd).args(args).current_dir(cwd).status();
    match status {
        Ok(s) if s.success() => {}
        Ok(s) => panic!("{label} failed with exit status {s}"),
        Err(e) => panic!(
            "{label} failed to spawn: {e}. Set ANANKE_SKIP_FRONTEND_BUILD=1 \
             to build without the embedded frontend."
        ),
    }
}
