//! Turns `tuning.json` into compile-time constants.
//!
//! This lives in its own crate so that regenerating the constants does not
//! rebuild the web UI. `tuning.json` is a `rerun-if-changed` input, and while
//! this generator sat in `ananke`'s build script it shared that script with the
//! frontend's `npm run build` — so every constant refresh during a calibration
//! campaign rebuilt the whole UI before the estimator would run.

use std::path::PathBuf;

fn main() {
    generate_tuning_constants();
}

/// Turn `tuning.json` into compile-time constants.
///
/// The JSON is generated by `ananke-calibrate`'s `emit` binary from the
/// measurement dataset, and it is the source of truth: the value a constant
/// has here *is* the value the estimator uses, so a number cannot drift from
/// the data that justifies it without the drift being visible in a diff of
/// the generated file. Each constant's `evidence` becomes part of its doc
/// comment, so the justification travels with the value rather than living in
/// a comment someone can forget to update.
fn generate_tuning_constants() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let source = manifest_dir.join("tuning.json");
    println!("cargo:rerun-if-changed={}", source.display());

    let raw = std::fs::read_to_string(&source)
        .unwrap_or_else(|e| panic!("reading {}: {e}", source.display()));
    let parsed: serde_json::Value =
        serde_json::from_str(&raw).unwrap_or_else(|e| panic!("parsing {}: {e}", source.display()));
    let constants = parsed
        .get("constants")
        .and_then(|c| c.as_object())
        .unwrap_or_else(|| panic!("{} has no `constants` object", source.display()));

    let mut out = String::from("// @generated by build.rs from tuning.json — do not edit.\n\n");
    for (name, spec) in constants {
        let ty = spec
            .get("type")
            .and_then(|v| v.as_str())
            .unwrap_or_else(|| panic!("{name}: missing `type`"));
        let raw = spec
            .get("value")
            .unwrap_or_else(|| panic!("{name}: missing `value`"));
        // A float literal has to keep its decimal point to be a float in
        // Rust, and an integer must not gain one.
        let value = if ty.starts_with('f') {
            let f = raw
                .as_f64()
                .unwrap_or_else(|| panic!("{name}: `value` is not a number"));
            if f.fract() == 0.0 {
                format!("{f:.1}")
            } else {
                f.to_string()
            }
        } else {
            raw.as_u64()
                .unwrap_or_else(|| panic!("{name}: `value` is not a non-negative integer"))
                .to_string()
        };
        let doc = spec.get("doc").and_then(|v| v.as_str()).unwrap_or("");
        let evidence = spec.get("evidence").and_then(|v| v.as_str()).unwrap_or("");

        for line in wrap(doc, 72) {
            out.push_str(&format!("/// {line}\n"));
        }
        out.push_str("///\n/// # Evidence\n///\n");
        for line in wrap(evidence, 72) {
            out.push_str(&format!("/// {line}\n"));
        }
        out.push_str(&format!("pub const {name}: {ty} = {value};\n\n"));
    }

    out.push_str(&generate_compute_model(&parsed));
    out.push_str(&generate_ik_rates(&parsed));
    out.push_str(&generate_rate_table(
        &parsed,
        "tensor_split_baseline",
        "TENSOR_SPLIT_BASELINE",
        "TENSOR_SPLIT_BASELINE_DEFAULT",
        "Extra host baseline bytes a tensor split costs beyond a layer split,\n/// by architecture.",
    ));
    out.push_str(&generate_signed_rate_table(
        &parsed,
        "baseline_offset",
        "BASELINE_OFFSET",
        "BASELINE_OFFSET_DEFAULT",
        "Correction to the process baseline the layer-count model leaves behind,\n/// by architecture and variant. Keys carry a `+moe`/`+e` suffix where those\n/// distinctions separate models that share an architecture string.",
    ));
    out.push_str(&generate_rate_table(
        &parsed,
        "checkpoint_headroom_bytes",
        "CHECKPOINT_HEADROOM_BYTES",
        "CHECKPOINT_HEADROOM_DEFAULT",
        "Host memory a real prompt adds over a short one, by architecture,\n/// from llama.cpp's context checkpoints. Reserved as slop.",
    ));
    out.push_str(&generate_rate_table(
        &parsed,
        "per_slot_host_bytes",
        "PER_SLOT_HOST_BYTES",
        "PER_SLOT_HOST_BYTES_DEFAULT",
        "Host memory each concurrently active slot costs beyond the first, by\n/// architecture. Reserved as slop, never charged to the correction.",
    ));
    out.push_str(&generate_rate_table(
        &parsed,
        "mtp_draft_compute_base_mib",
        "MTP_DRAFT_COMPUTE_BASE_MIB",
        "MTP_DRAFT_COMPUTE_BASE_MIB_DEFAULT",
        "The MTP draft context's own per-device compute buffer at zero context, by\n/// architecture.",
    ));
    out.push_str(&generate_rate_table(
        &parsed,
        "mtp_draft_compute_mib_per_1k",
        "MTP_DRAFT_COMPUTE_MIB_PER_1K",
        "MTP_DRAFT_COMPUTE_MIB_PER_1K_DEFAULT",
        "Slope of that buffer, in thousandths of a MiB per 1024 context tokens.",
    ));
    out.push_str(&generate_rate_table(
        &parsed,
        "no_flash_attn_score_centibytes",
        "NO_FLASH_ATTN_SCORE_CENTIBYTES",
        "NO_FLASH_ATTN_SCORE_CENTIBYTES_DEFAULT",
        "Bytes of unfused attention score matrix per (head x cache token x batch\n/// token), by architecture.",
    ));
    out.push_str(&generate_rate_table(
        &parsed,
        "no_flash_attn_rates",
        "NO_FLASH_ATTN_RATES",
        "NO_FLASH_ATTN_RATE_DEFAULT",
        "Extra pinned bytes per batch token when flash attention is off, by\n/// architecture and variant. Flat in context, proportional to batch.",
    ));
    out.push_str(&generate_rate_table(
        &parsed,
        "quantised_cache_rates",
        "QUANTISED_CACHE_RATES",
        "QUANTISED_CACHE_RATE_DEFAULT",
        "Extra pinned bytes per batch token when the KV cache is quantised, by\n/// architecture.",
    ));

    let dest = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("tuning_constants.rs");
    std::fs::write(&dest, out).unwrap_or_else(|e| panic!("writing {}: {e}", dest.display()));
}

/// Turn the ordered compute-buffer curve table into a static slice.
///
/// The architecture-to-curve mapping is data, not logic: adding an
/// architecture should be a JSON edit, not a new match arm. Order is
/// significant and preserved — the first entry whose arch list contains the
/// model's architecture wins, so a variant-guarded entry has to precede the
/// general one for the same arch.
/// The column names of the unified per-device compute model, in the order the
/// generated struct declares its fields.
///
/// The list is checked against the `columns` array in `tuning.json` rather than
/// trusted: the fitter and the evaluator have to agree on what each coefficient
/// multiplies, and a column silently added on one side is exactly the drift the
/// generated-constant scheme exists to prevent.
const COMPUTE_MODEL_COLUMNS: &[&str] = &[
    "flat",
    "head_flat",
    "hidden",
    "doubling",
    "mask",
    "quant",
    "logits",
    "offload_head",
];

/// Turn the `compute_model` section into coefficient tables.
///
/// One entry per (runtime, split, architecture, variant), each holding the
/// coefficient of every column the fit could identify for that group. A column
/// the group did not identify is absent from the JSON and generated as zero,
/// which is the same thing: a term the data gave no evidence for contributes
/// nothing.
/// Per-architecture rates for ik's CPU-resident MoE intermediates.
///
/// One number cannot serve every architecture: the measured rates differ by a
/// third, so a single value either under-reserves the worst or over-reserves
/// the rest.
fn generate_ik_rates(parsed: &serde_json::Value) -> String {
    let Some(rates) = parsed.get("ik_moe_rates") else {
        return String::new();
    };
    let default = rates.get("default").and_then(|v| v.as_u64()).unwrap_or(0);
    let by_arch = rates.get("by_arch").and_then(|v| v.as_object());
    let mut out = String::from(
        "\n/// Bytes per batch token per unit of hidden size for ik's \
         CPU-resident\n/// MoE intermediates, by architecture.\n\
         pub static IK_MOE_RATES: &[(&str, u64)] = &[\n",
    );
    if let Some(map) = by_arch {
        for (arch, value) in map {
            out.push_str(&format!(
                "    ({arch:?}, {}),\n",
                value.as_u64().unwrap_or(default)
            ));
        }
    }
    out.push_str(
        "];\n\n/// Applied to an ik mixture of experts this dataset has \
                  not measured.\npub const IK_MOE_RATE_DEFAULT: u64 = ",
    );
    out.push_str(&default.to_string());
    out.push_str(";\n");
    out
}

fn generate_compute_model(parsed: &serde_json::Value) -> String {
    let model = match parsed.get("compute_model") {
        Some(m) => m,
        None => return String::new(),
    };

    let declared: Vec<&str> = model
        .get("columns")
        .and_then(|c| c.as_array())
        .unwrap_or_else(|| panic!("compute_model has no `columns` array"))
        .iter()
        .map(|c| {
            c.as_str()
                .unwrap_or_else(|| panic!("compute_model column is not a string"))
        })
        .collect();
    assert_eq!(
        declared, COMPUTE_MODEL_COLUMNS,
        "compute_model columns in tuning.json do not match the generated struct; \
         update COMPUTE_MODEL_COLUMNS in build.rs and the evaluator together"
    );

    let mut out = String::from(
        "\n/// Coefficients of the unified per-device compute model, one set per\n\
         /// (runtime, split, architecture, variant). Each multiplies the like-named\n\
         /// column built by [`crate::estimator::compute_model::Columns`]; the total is\n\
         /// that card's compute reservation in MiB.\n\
         ///\n\
         /// `flat`, `head_flat`, and `doubling` are MiB outright. The rest are bytes\n\
         /// per element, their columns having been divided by 2^20 when built, so the\n\
         /// dot product comes out in MiB throughout.\n\
         #[derive(Debug, Clone, Copy, PartialEq)]\n\
         pub struct ComputeCoefficients {\n",
    );
    for column in COMPUTE_MODEL_COLUMNS {
        out.push_str(&format!("    pub {column}: f64,\n"));
    }
    out.push_str(
        "}\n\n\
         /// One fitted group of the compute model.\n\
         #[derive(Debug, Clone, Copy)]\n\
         pub struct ComputeEntry {\n\
         \x20   /// Architectures this entry applies to.\n\
         \x20   pub archs: &'static [&'static str],\n\
         \x20   /// A variant discriminator the caller must also match, where one\n\
         \x20   /// architecture string covers models with different graphs.\n\
         \x20   pub variant: Option<&'static str>,\n\
         \x20   /// The serving runtime this group was fitted against, or `None` for\n\
         \x20   /// one that applies to either fork.\n\
         \x20   pub runtime: Option<&'static str>,\n\
         \x20   /// `\"layer\"` or `\"tensor\"`.\n\
         \x20   pub split: &'static str,\n\
         \x20   pub coefficients: ComputeCoefficients,\n\
         }\n\n",
    );

    let entries = model
        .get("entries")
        .and_then(|e| e.as_array())
        .unwrap_or_else(|| panic!("compute_model has no `entries` array"));
    out.push_str(
        "/// Ordered; first match wins.\npub static COMPUTE_MODEL: &[ComputeEntry] = &[\n",
    );
    for entry in entries {
        let archs = entry
            .get("archs")
            .and_then(|a| a.as_array())
            .unwrap_or_else(|| panic!("compute_model entry has no `archs`"))
            .iter()
            .map(|a| format!("{:?}", a.as_str().expect("arch is not a string")))
            .collect::<Vec<_>>()
            .join(", ");
        let optional = |key: &str| match entry.get(key).and_then(|v| v.as_str()) {
            Some(value) => format!("Some({value:?})"),
            None => "None".to_string(),
        };
        let split = entry
            .get("split")
            .and_then(|v| v.as_str())
            .unwrap_or_else(|| panic!("compute_model entry has no `split`"));
        out.push_str(&format!(
            "    ComputeEntry {{\n\
             \x20       archs: &[{archs}],\n\
             \x20       variant: {},\n\
             \x20       runtime: {},\n\
             \x20       split: {split:?},\n\
             \x20       coefficients: {},\n\
             \x20   }},\n",
            optional("variant"),
            optional("runtime"),
            coefficients_literal(entry),
        ));
    }
    out.push_str("];\n\n");

    let default = model
        .get("default")
        .unwrap_or_else(|| panic!("compute_model has no `default`"));
    out.push_str(
        "/// Used by any (runtime, split, architecture) without its own entry.\n\
         pub static COMPUTE_MODEL_DEFAULT: ComputeCoefficients = ",
    );
    out.push_str(&coefficients_literal(default));
    out.push_str(";\n");
    out
}

/// A `ComputeCoefficients` literal from an entry's `coefficients` object,
/// filling every column the fit left out with zero.
fn coefficients_literal(entry: &serde_json::Value) -> String {
    let coefficients = entry
        .get("coefficients")
        .and_then(|c| c.as_object())
        .unwrap_or_else(|| panic!("compute_model entry has no `coefficients` object"));
    for name in coefficients.keys() {
        assert!(
            COMPUTE_MODEL_COLUMNS.contains(&name.as_str()),
            "compute_model entry has unknown coefficient `{name}`"
        );
    }
    let fields = COMPUTE_MODEL_COLUMNS
        .iter()
        .map(|column| {
            let value = coefficients
                .get(*column)
                .and_then(|v| v.as_f64())
                .unwrap_or(0.0);
            format!("{column}: {value:?}")
        })
        .collect::<Vec<_>>()
        .join(", ");
    format!("ComputeCoefficients {{ {fields} }}")
}

/// A per-architecture rate table: `&[(arch, value)]` plus a default.
/// The same table, for values that may be negative.
///
/// `baseline_offset` corrects a baseline that over-covers as well as one that
/// under-covers, so its entries are signed. Reading them through the unsigned
/// path silently turns every negative into the default, which is zero — the
/// correction would vanish rather than fail.
fn generate_signed_rate_table(
    parsed: &serde_json::Value,
    key: &str,
    table: &str,
    default_name: &str,
    doc: &str,
) -> String {
    let Some(rates) = parsed.get(key) else {
        return String::new();
    };
    let default = rates.get("default").and_then(|v| v.as_i64()).unwrap_or(0);
    let mut out = format!("\n/// {doc}\npub static {table}: &[(&str, i64)] = &[\n");
    if let Some(map) = rates.get("by_arch").and_then(|v| v.as_object()) {
        for (arch, value) in map {
            out.push_str(&format!(
                "    ({arch:?}, {}),\n",
                value.as_i64().unwrap_or(default)
            ));
        }
    }
    out.push_str(&format!(
        "];\n\n/// Applied to an architecture this dataset has not measured.\n\
         pub const {default_name}: i64 = {default};\n"
    ));
    out
}

fn generate_rate_table(
    parsed: &serde_json::Value,
    key: &str,
    table: &str,
    default_name: &str,
    doc: &str,
) -> String {
    let Some(rates) = parsed.get(key) else {
        return String::new();
    };
    let default = rates.get("default").and_then(|v| v.as_u64()).unwrap_or(0);
    let mut out = format!("\n/// {doc}\npub static {table}: &[(&str, u64)] = &[\n");
    if let Some(map) = rates.get("by_arch").and_then(|v| v.as_object()) {
        for (arch, value) in map {
            out.push_str(&format!(
                "    ({arch:?}, {}),\n",
                value.as_u64().unwrap_or(default)
            ));
        }
    }
    out.push_str(&format!(
        "];\n\n/// Applied to an architecture this dataset has not measured.\n\
         pub const {default_name}: u64 = {default};\n"
    ));
    out
}

/// Break `text` into lines of at most `width`, so generated doc comments do
/// not arrive as one unreadable line.
fn wrap(text: &str, width: usize) -> Vec<String> {
    let mut lines = Vec::new();
    let mut current = String::new();
    for word in text.split_whitespace() {
        if !current.is_empty() && current.len() + 1 + word.len() > width {
            lines.push(std::mem::take(&mut current));
        }
        if !current.is_empty() {
            current.push(' ');
        }
        current.push_str(word);
    }
    if !current.is_empty() {
        lines.push(current);
    }
    if lines.is_empty() {
        lines.push(String::new());
    }
    lines
}
