//! Turns `tuning.json` into compile-time constants.
//!
//! This lives in its own crate so that regenerating the constants does not
//! rebuild the web UI. `tuning.json` is a `rerun-if-changed` input, and while
//! this generator sat in `ananke`'s build script it shared that script with the
//! frontend's `npm run build` — so every constant refresh during a calibration
//! campaign rebuilt the whole UI before the estimator would run.
//!
//! The document is read through `ananke-tuning-schema`, which is why that crate
//! exists at all: a build script cannot depend on the crate it builds, so the
//! type the derivers write against has to sit below both.

use std::{collections::BTreeMap, path::PathBuf};

use ananke_tuning_schema::{
    ConstantValue, Document, RateTable, RateTableName,
    compute_model::{Fit, Section},
};

fn main() {
    generate_tuning_constants();
}

/// Turn `tuning.json` into compile-time constants.
///
/// The JSON is generated by `ananke-calibrate`'s `emit` binary from the
/// measurement dataset, and it is the source of truth: the value a constant
/// has here *is* the value the estimator uses, so a number cannot drift from
/// the data that justifies it without the drift being visible in a diff of
/// the generated file. Each constant's `evidence` becomes part of its doc
/// comment, so the justification travels with the value rather than living in
/// a comment someone can forget to update.
fn generate_tuning_constants() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let source = manifest_dir.join("tuning.json");
    println!("cargo:rerun-if-changed={}", source.display());

    let raw = std::fs::read_to_string(&source)
        .unwrap_or_else(|e| panic!("reading {}: {e}", source.display()));
    let document: Document =
        serde_json::from_str(&raw).unwrap_or_else(|e| panic!("parsing {}: {e}", source.display()));

    let mut out = String::from("// @generated by build.rs from tuning.json — do not edit.\n\n");
    for (name, spec) in &document.constants {
        // A float literal has to keep its decimal point to be a float in Rust,
        // and an integer must not gain one.
        let value = match spec
            .typed()
            .unwrap_or_else(|error| panic!("{name}: {error}"))
        {
            ConstantValue::F64(f) if f.fract() == 0.0 => format!("{f:.1}"),
            ConstantValue::F64(f) => f.to_string(),
            ConstantValue::U32(v) => v.to_string(),
            ConstantValue::U64(v) => v.to_string(),
        };

        for line in wrap(&spec.doc, 72) {
            out.push_str(&format!("/// {line}\n"));
        }
        out.push_str("///\n/// # Evidence\n///\n");
        for line in wrap(&spec.evidence, 72) {
            out.push_str(&format!("/// {line}\n"));
        }
        out.push_str(&format!(
            "pub const {name}: {} = {value};\n\n",
            spec.ty.as_str()
        ));
    }

    out.push_str(&generate_compute_model(&document.compute_model));
    for table in rate_tables(&document) {
        out.push_str(&generate_rate_table(&table));
    }

    let dest = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("tuning_constants.rs");
    std::fs::write(&dest, out).unwrap_or_else(|e| panic!("writing {}: {e}", dest.display()));
}

/// The column names of the unified per-device compute model, in the order the
/// generated struct declares its fields.
///
/// The list is checked against the `columns` array in `tuning.json` rather than
/// trusted: the fitter and the evaluator have to agree on what each coefficient
/// multiplies, and a column silently added on one side is exactly the drift the
/// generated-constant scheme exists to prevent.
const COMPUTE_MODEL_COLUMNS: &[&str] = &[
    "flat",
    "head_flat",
    "hidden",
    "doubling",
    "mask",
    "quant",
    "logits",
    "offload_head",
];

/// Turn the `compute_model` section into coefficient tables.
///
/// One entry per (runtime, split, architecture, variant), each holding the
/// coefficient of every column the fit could identify for that group. A column
/// the group did not identify is absent from the JSON and generated as zero,
/// which is the same thing: a term the data gave no evidence for contributes
/// nothing. Order is significant and preserved — the first entry whose arch list
/// contains the model's architecture wins, so a variant-guarded entry has to
/// precede the general one for the same arch.
fn generate_compute_model(model: &Section) -> String {
    let declared: Vec<&str> = model.columns.iter().map(String::as_str).collect();
    assert_eq!(
        declared, COMPUTE_MODEL_COLUMNS,
        "compute_model columns in tuning.json do not match the generated struct; \
         update COMPUTE_MODEL_COLUMNS in build.rs and the evaluator together"
    );

    let mut out = String::from(
        "\n/// Coefficients of the unified per-device compute model, one set per\n\
         /// (runtime, split, architecture, variant). Each multiplies the like-named\n\
         /// column built by [`crate::estimator::compute_model::Columns`]; the total is\n\
         /// that card's compute reservation in MiB.\n\
         ///\n\
         /// `flat`, `head_flat`, and `doubling` are MiB outright. The rest are bytes\n\
         /// per element, their columns having been divided by 2^20 when built, so the\n\
         /// dot product comes out in MiB throughout.\n\
         #[derive(Debug, Clone, Copy, PartialEq)]\n\
         pub struct ComputeCoefficients {\n",
    );
    for column in COMPUTE_MODEL_COLUMNS {
        out.push_str(&format!("    pub {column}: f64,\n"));
    }
    out.push_str(
        "}\n\n\
         /// One fitted group of the compute model.\n\
         #[derive(Debug, Clone, Copy)]\n\
         pub struct ComputeEntry {\n\
         \x20   /// Architectures this entry applies to.\n\
         \x20   pub archs: &'static [&'static str],\n\
         \x20   /// A variant discriminator the caller must also match, where one\n\
         \x20   /// architecture string covers models with different graphs.\n\
         \x20   pub variant: Option<&'static str>,\n\
         \x20   /// The serving runtime this group was fitted against, or `None` for\n\
         \x20   /// one that applies to either fork.\n\
         \x20   pub runtime: Option<&'static str>,\n\
         \x20   /// `\"layer\"` or `\"tensor\"`.\n\
         \x20   pub split: &'static str,\n\
         \x20   pub coefficients: ComputeCoefficients,\n\
         }\n\n",
    );

    out.push_str(
        "/// Ordered; first match wins.\npub static COMPUTE_MODEL: &[ComputeEntry] = &[\n",
    );
    for entry in &model.entries {
        let archs = entry
            .archs
            .iter()
            .map(|arch| format!("{arch:?}"))
            .collect::<Vec<_>>()
            .join(", ");
        let optional = |guard: &Option<String>| match guard {
            Some(value) => format!("Some({value:?})"),
            None => "None".to_string(),
        };
        let split = &entry.split;
        out.push_str(&format!(
            "    ComputeEntry {{\n\
             \x20       archs: &[{archs}],\n\
             \x20       variant: {},\n\
             \x20       runtime: {},\n\
             \x20       split: {split:?},\n\
             \x20       coefficients: {},\n\
             \x20   }},\n",
            optional(&entry.variant),
            optional(&entry.runtime),
            coefficients_literal(&entry.coefficients),
        ));
    }
    out.push_str("];\n\n");

    out.push_str(
        "/// Used by any (runtime, split, architecture) without its own entry.\n\
         pub static COMPUTE_MODEL_DEFAULT: ComputeCoefficients = ",
    );
    let Fit { coefficients, .. } = &model.default;
    out.push_str(&coefficients_literal(coefficients));
    out.push_str(";\n");
    out
}

/// A `ComputeCoefficients` literal from one group's coefficients, filling every
/// column the fit left out with zero.
fn coefficients_literal(coefficients: &BTreeMap<String, f64>) -> String {
    for name in coefficients.keys() {
        assert!(
            COMPUTE_MODEL_COLUMNS.contains(&name.as_str()),
            "compute_model entry has unknown coefficient `{name}`"
        );
    }
    let fields = COMPUTE_MODEL_COLUMNS
        .iter()
        .map(|column| {
            let value = coefficients.get(*column).copied().unwrap_or(0.0);
            format!("{column}: {value:?}")
        })
        .collect::<Vec<_>>()
        .join(", ");
    format!("ComputeCoefficients {{ {fields} }}")
}

/// One rate table, and the names and prose its generated constants take.
struct Generated<'a> {
    name: RateTableName,
    table: &'a RateTable,
    /// The generated slice's name.
    slice: &'static str,
    /// The generated fallback constant's name.
    default: &'static str,
    doc: &'static str,
    default_doc: &'static str,
}

/// Every rate table, in the order the generated file declares them.
///
/// Built by field access and then checked against [`Document::rate_tables`], so
/// a table added to the schema and forgotten here fails the build rather than
/// quietly ceasing to be a constant.
fn rate_tables(document: &Document) -> Vec<Generated<'_>> {
    const UNMEASURED: &str = "Applied to an architecture this dataset has not measured.";
    let generated = vec![
        Generated {
            name: RateTableName::IkMoeRates,
            table: &document.ik_moe_rates,
            slice: "IK_MOE_RATES",
            default: "IK_MOE_RATE_DEFAULT",
            doc: "Bytes per batch token per unit of hidden size for ik's CPU-resident\n\
                  /// MoE intermediates, by architecture.",
            default_doc: "Applied to an ik mixture of experts this dataset has not measured.",
        },
        Generated {
            name: RateTableName::TensorSplitBaseline,
            table: &document.tensor_split_baseline,
            slice: "TENSOR_SPLIT_BASELINE",
            default: "TENSOR_SPLIT_BASELINE_DEFAULT",
            doc: "Extra host baseline bytes a tensor split costs beyond a layer split,\n\
                  /// by architecture.",
            default_doc: UNMEASURED,
        },
        Generated {
            name: RateTableName::BaselineOffset,
            table: &document.baseline_offset,
            slice: "BASELINE_OFFSET",
            default: "BASELINE_OFFSET_DEFAULT",
            doc: "Correction to the process baseline the layer-count model leaves behind,\n\
                  /// by architecture and variant. Keys carry a `+moe`/`+e` suffix where those\n\
                  /// distinctions separate models that share an architecture string.",
            default_doc: UNMEASURED,
        },
        Generated {
            name: RateTableName::CheckpointHeadroomBytes,
            table: &document.checkpoint_headroom_bytes,
            slice: "CHECKPOINT_HEADROOM_BYTES",
            default: "CHECKPOINT_HEADROOM_DEFAULT",
            doc: "Host memory a real prompt adds over a short one, by architecture,\n\
                  /// from llama.cpp's context checkpoints. Reserved as slop.",
            default_doc: UNMEASURED,
        },
        Generated {
            name: RateTableName::PerSlotHostBytes,
            table: &document.per_slot_host_bytes,
            slice: "PER_SLOT_HOST_BYTES",
            default: "PER_SLOT_HOST_BYTES_DEFAULT",
            doc: "Host memory each concurrently active slot costs beyond the first, by\n\
                  /// architecture. Reserved as slop, never charged to the correction.",
            default_doc: UNMEASURED,
        },
        Generated {
            name: RateTableName::MtpDraftComputeBaseMib,
            table: &document.mtp_draft_compute_base_mib,
            slice: "MTP_DRAFT_COMPUTE_BASE_MIB",
            default: "MTP_DRAFT_COMPUTE_BASE_MIB_DEFAULT",
            doc: "The MTP draft context's own per-device compute buffer at zero context, by\n\
                  /// architecture.",
            default_doc: UNMEASURED,
        },
        Generated {
            name: RateTableName::MtpDraftComputeMibPer1k,
            table: &document.mtp_draft_compute_mib_per_1k,
            slice: "MTP_DRAFT_COMPUTE_MIB_PER_1K",
            default: "MTP_DRAFT_COMPUTE_MIB_PER_1K_DEFAULT",
            doc: "Slope of that buffer, in thousandths of a MiB per 1024 context tokens.",
            default_doc: UNMEASURED,
        },
        Generated {
            name: RateTableName::NoFlashAttnScoreCentibytes,
            table: &document.no_flash_attn_score_centibytes,
            slice: "NO_FLASH_ATTN_SCORE_CENTIBYTES",
            default: "NO_FLASH_ATTN_SCORE_CENTIBYTES_DEFAULT",
            doc: "Bytes of unfused attention score matrix per (head x cache token x batch\n\
                  /// token), by architecture.",
            default_doc: UNMEASURED,
        },
        Generated {
            name: RateTableName::NoFlashAttnRates,
            table: &document.no_flash_attn_rates,
            slice: "NO_FLASH_ATTN_RATES",
            default: "NO_FLASH_ATTN_RATE_DEFAULT",
            doc: "Extra pinned bytes per batch token when flash attention is off, by\n\
                  /// architecture and variant. Flat in context, proportional to batch.",
            default_doc: UNMEASURED,
        },
        Generated {
            name: RateTableName::QuantisedCacheRates,
            table: &document.quantised_cache_rates,
            slice: "QUANTISED_CACHE_RATES",
            default: "QUANTISED_CACHE_RATE_DEFAULT",
            doc: "Extra pinned bytes per batch token when the KV cache is quantised, by\n\
                  /// architecture.",
            default_doc: UNMEASURED,
        },
    ];
    for (name, _) in document.rate_tables() {
        assert!(
            generated.iter().any(|table| table.name == name),
            "{} has no generated constants; add it to build.rs's rate_tables",
            name.as_str()
        );
    }
    generated
}

/// A per-architecture rate table: `&[(arch, value)]` plus a default.
///
/// A signed table is emitted as `i64`. `baseline_offset` corrects a baseline
/// that over-covers as well as one that under-covers, and reading its entries
/// through the unsigned path silently turns every negative into the default,
/// which is zero — the correction would vanish rather than fail.
fn generate_rate_table(generated: &Generated<'_>) -> String {
    let Generated {
        name,
        table,
        slice,
        default,
        doc,
        default_doc,
    } = generated;
    let ty = if name.signed() { "i64" } else { "u64" };
    let fallback = render(table.default, name.signed(), 0);
    let mut out = format!("\n/// {doc}\npub static {slice}: &[(&str, {ty})] = &[\n");
    for (arch, value) in &table.by_arch {
        out.push_str(&format!(
            "    ({arch:?}, {}),\n",
            render(*value, name.signed(), table.default)
        ));
    }
    out.push_str(&format!(
        "];\n\n/// {default_doc}\npub const {default}: {ty} = {fallback};\n"
    ));
    out
}

/// One entry, as the generated table spells it. An unsigned table cannot carry a
/// negative, so one falls back to the table's default the way `as_u64` always did.
fn render(value: i64, signed: bool, fallback: i64) -> String {
    if signed {
        return value.to_string();
    }
    u64::try_from(value)
        .unwrap_or_else(|_| u64::try_from(fallback).unwrap_or(0))
        .to_string()
}

/// Break `text` into lines of at most `width`, so generated doc comments do
/// not arrive as one unreadable line.
fn wrap(text: &str, width: usize) -> Vec<String> {
    let mut lines = Vec::new();
    let mut current = String::new();
    for word in text.split_whitespace() {
        if !current.is_empty() && current.len() + 1 + word.len() > width {
            lines.push(std::mem::take(&mut current));
        }
        if !current.is_empty() {
            current.push(' ');
        }
        current.push_str(word);
    }
    if !current.is_empty() {
        lines.push(current);
    }
    if lines.is_empty() {
        lines.push(String::new());
    }
    lines
}
